version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      args:
        - ENVIRONMENT=production
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend

  backend:
    build:
      context: ./api
      args:
        - ENVIRONMENT=production
    expose:
      - "8000"
    environment:
      - ENVIRONMENT=production
    volumes:
      - ./api/logs:/app/logs

  nginx:
    image: nginx:alpine
    ports:
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/build:/usr/share/nginx/html
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - frontend
      - backend

networks:
  default:
    driver: bridge