version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://backend:8000
    depends_on:
      - backend

  backend:
    build: ./api
    ports:
      - "8000:8000"
    volumes:
      - ./api/logs:/app/logs

networks:
  default:
    driver: bridge